version: "3"
services:
  db:
    container_name: db_pizzaneves
    image: postgres:11.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pingo2009
      POSTGRES_DB: pizzaneves



